# Generated by Django 5.0.4 on 2024-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
